---
- name: Ensure ~/.gitconfig is copied from master.gitconfig
  hosts: localhost
  gather_facts: false
  tasks:
  - copy: src="../adhoc/master.gitconfig" dest="~/.gitconfig"

- name: Ensure homebrew packages are installed
  hosts: localhost
  tasks:
  - homebrew: name=bat state=latest
  - homebrew:
      name: jq
      state: latest
