---
# ansible -m copy -a "src=../adhoc/master.giconfig" dest=~/.gitconfig" localhost
- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: localhost
  tasks:
  - copy: src="../adhoc/master.gitconfig" dest="~/.gitconfig"
